{
    "name": "Microsoft 365 - OneDrive y SharePoint",
    "version": "19.0.2.0.0",
    "summary": "OneDrive, SharePoint, invitados, grupos y administración Microsoft 365",
    "author": "Copier Company SAC",
    "category": "Productivity/Documents",
    "license": "LGPL-3",
    "depends": ["base", "web", "mail"],
    "data": [
        "security/microsoft_security.xml",
        "security/ir.model.access.csv",
        "security/microsoft_record_rules.xml",
        "data/ir_config_parameter.xml",
        "data/ir_cron.xml",
        "views/microsoft_tenant_views.xml",
        "views/microsoft_guest_views.xml",
        "views/microsoft_group_views.xml",
        "views/sharepoint_site_views.xml",
        "views/storage_location_views.xml",
        "views/res_users_views.xml",
        "views/microsoft_audit_views.xml",
        "wizard/microsoft_access_wizard_views.xml",
        "views/legacy_compat.xml",
        "views/microsoft_menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "odoo_onedrive_integration/static/src/scss/bootstrap_icons.scss",
            "odoo_onedrive_integration/static/src/scss/onedrive_app.scss",
            "odoo_onedrive_integration/static/src/js/utils/file_utils.js",
            "odoo_onedrive_integration/static/src/js/dialogs/confirm_dialog.js",
            "odoo_onedrive_integration/static/src/js/dialogs/prompt_dialog.js",
            "odoo_onedrive_integration/static/src/js/dialogs/file_preview_dialog.js",
            "odoo_onedrive_integration/static/src/js/dialogs/share_dialog.js",
            "odoo_onedrive_integration/static/src/js/dialogs/properties_dialog.js",
            "odoo_onedrive_integration/static/src/js/onedrive_app.js",
            "odoo_onedrive_integration/static/src/xml/onedrive_templates.xml",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
}
